image:
  tag: {{ .Env.IMAGE_TAG }}
db:
  user: todo
  # Set in ansible
  # password: {{ lookup('amazon.aws.aws_secret' item) }}
config:
  postgresDB: todo_app
  postgresHost: {{ (datasource "config").rds_endpoint }}
ingress:
  enabled: true
  className: kubernetes.io/ingress.class: nginx
  cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: main-ingress-tls

  hosts:
    - host: {{ (datasource "config").backend_api_url }}
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: {{ .Env.}}
