# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
      name: Fix trailing whitespace
    - id: check-yaml
      exclude: '(.github\/workflows|infra/.*)'
      name: Validate YAML
    - id: check-added-large-files
      name: Check for large added files
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [flake8-typing-imports==1.10.0]
      args: ['-v']
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: scripts/unit.sh
        language: script
        stages: [commit]
