version: '3'

services:
  db:
    image: postgres:alpine
    ports: 
      - 5432:5432
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data:z
  app:
    image: joelfreeman/todo-backend:latest
    volumes:
      - ./src/:/home/todoapp/src/:z
    ports:
      - 8080:8080
    env_file: .env
    command: web
    depends_on: ['db']
  nginx:
    image: nginx:1.14.2
    ports:
      - 80:80
    volumes:
      - ./infra/conf/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:z
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx/"
      NGINX_BACKEND: "app"
    depends_on: ['app']
volumes:
  data: