

module "todo_app" {
  source = "./todo-app"

  environment_name = "development"
  branch_name      = ""
  api_url          = "api.branch.dev.tinakori.dev"
  frontend_url     = "branch.dev.tinakori.dev"
  docker_image_tag = "latest"

}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform todo_app configuration.

    secretsmanager_secret_name: ${module.todo_app.db_todo_user_secretsmanager_name}
    secretsmanager_root_secret_name: ${module.todo_app.db_root_user_secretsmanager_name}
    rds_endpoint: ${module.todo_app.rds_endpoint}
    backend_api_url: ${module.todo_app.api_url}
    frontend_url: ${module.todo_app.frontend_url}
    rds_root_user: ${module.todo_app.rds_root_user}
    DOC
  filename = "./tf_ansible_vars_file.yml"
}
