apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ b64enc .Values.db.user }}
  POSTGRES_PASSWORD: {{ b64enc .Values.db.password }}
