# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
- clusterissuer.yaml
- namespace.yaml
secretGenerator:
- name: cloudflare-apikey
  namespace: cert-manager
  type: Opaque
  files:
  - apikey