apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-backend.fullname" . }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
data:
    POSTGRES_HOST: {{ .Values.postgres_host | quote }}
    CORS_ALLOWED_ORIGINS: {{ .Values.cors_allowed_origins | quote }}
    ENV: {{ .Values.env | quote }}
