name: Build Docker Image
on:
  push:
    tags: v[1-9]+[0-9]+.[0-9]+
    branches: master
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

  docker-build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Calculate tags
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          export GIT_TAG_NAME=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: .
          push: true
          tags: joelfreeman/todo-backend:${{ env.GITHUB_SHA }}, joelfreeman/todo-backend:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: .
          push: true
          tags: joelfreeman/todo-backend:${{ env.GITHUB_SHA }}, joelfreeman/todo-backend:${{ env.GIT_TAG_NAME }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
      
