name: Build Docker Image
on:
  push:
    tags: v[1-9]+[0-9]+.[0-9]+
    branches: '**'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os}}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Calculate tags
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          export GIT_TAG_NAME=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)

      - name: Create docker tag variable
        id: tags
        run: | 
          echo "::set-output name=branch_name::$(git branch --no-color --show-current)-$(git rev-parse --short HEAD)"
      
      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        with:
          context: .
          push: true
          tags: |
            joelfreeman/todo-backend:${{ steps.tags.outputs.branch_name }}
            joelfreeman/todo-backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build and push (tag)
        uses: docker/build-push-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: .
          push: true
          tags: |
            joelfreeman/todo-backend:latest, 
            joelfreeman/todo-backend:${{ env.GIT_TAG_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache          
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install linter
        run: pip install flake8
      
      - name: Run linter
        run: flake8
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Copy env file
        run: cp .env.testing .env

      - name: Start postgres
        run: docker-compose up -d db

      - name: Pull latest app image
        run: |
          docker-compose pull app

      - name: Run database migrations
        run: docker-compose run --rm app migrate

      - name: Run unit tests
        run: docker-compose run --rm app test
  

      