name: Deploy AWS Resources
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Name of branch / environment to deploy to."
        required: true
      image-tag:
        description: "Docker image tag to deploy"
        required: true

jobs:
  deploy-to-dev:
    # dev-cluster-runner
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
      - uses: hashicorp/setup-terraform@v1

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
          web-identity-token-file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      
      - name: get-caller-identity
        run: |
          aws sts get-caller-identity

   deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
      - uses: hashicorp/setup-terraform@v1

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
          web-identity-token-file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      
      - name: get-caller-identity
        run: |
          aws sts get-caller-identity
      